### ISSUE TITLE
Core file tests in daemon fail on most modern Linux systems

### ISSUE THREAD

**Issue by johnsonjh** [raforg/libslack#1]
This is because most systemd systems set the sysctl kernel.core_pattern to a pipe for processing, for example `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h`. Even before that, it was a common default to see `"${HOME}/.cores"` or similar.

A workaround is setting `kernel.core_pattern` to a compatible value, or, (manually or otherwise) verifying that the core files are indeed produced; on my system, they're found in `/cores`, which is a symlink to `/var/lib/systemd/coredump/`

A minor issue overall. It would probably be best to just give a warning rather than fail this test. 

I believe the complexity of parsing the kernel.core_pattern sysctl variable to detect the core path, or worse, detecting the systemd case and parsing the output of systemd's `coredumpctl` utility isn't warranted here.

**Comment by raforg** [comment]
Thanks for that. I'm used to those tests failing on macOS because cores go in /cores, but "ulimit -c 0" seems to be the default in my shell, so it fails on Debian 10 (stable) as well. But if I "ulimit -c 1000000", then the tests work on my Debian 10 system (where kernel.core_pattern=core). But they still don't work on macOS (or other systems that put cores in funny places).

The test failure messages already suggest that ulimit might be the cause. So that's like a warning.

And if a function (dump) is supposed to dump core and it doesn't, that should fail its test.

But a definite improvement can be made. If I test that the core dump happened by using WCOREDUMP() on the waitpid() status, rather than looking for actual core files, those tests should only fail when it really is ulimit that is preventing core dumps. That way, the suggestion that ulimit is prevent the test from passing would be much more likely to be accurate.

I still wouldn't be able to clean up centralized core files after the test, but presumably such systems regularly clean up old core files since they're all in the same place and easily managed.

Actually, I just checked the documentation. It doesn't say anything about core files. It says:

    Outputs an error message to the program's error message destination and then calls abort(3).

It already fails the test if it wasn't terminated with SIGABRT. So the absence of, or inability to find, core files shouldn't matter (except that I can't delete them after the test). It might not even need to issue a warning.

Thanks again.

**Comment by raforg** [comment]
I've changed it so that it tests for core dumps with WCOREDUMP() (if available) rather than looking for actual files in the current directory. And it only emits a warning if the absence of a core dump isn't due to resource limits/ulimit (it checks). Any centralised core files won't get deleted, but that's probably fine. It will still delete a local core file with an expected name if it's there.
